apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: job-pyspark-{{ macros.datetime.now().strftime("%Y-%m-%d-%H-%M-%S") }}
  namespace: airflow
spec:
  volumes:
    - name: ivy
      emptyDir: {}
    spark.kubernetes.allocation.batch.size: "10"
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "docker.io/neylsoncrepalde/spark-operator:v3.0.0-aws"
  imagePullPolicy: Always
  mainApplicationFile: s3://codes-pyspark-608636080729/spark-operator-enem.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  driver:
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
    cores: 1
    instances: 2
    coreLimit: "1200m"
    memory: "8g"
    labels:
      version: 3.0.0
    serviceAccount: airflow-worker
    volumeMounts:
      - name: ivy
        mountPath: /tmp
  executor:
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
    cores: 2
    instances: 2
    memory: "4g"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: ivy
        mountPath: /tmp